### PR TITLE
First pass at making snakemake workflow for innovation model

### PR DESCRIPTION
**Pull request by marlinfiggins**
This PR implements a Snakemake workflow for provisioning sequence counts with similar methods used in [forecasts-ncov](https://github.com/nextstrain/forecasts-ncov). This is my first time working with Snakemake, so any suggestions, comments, or questions are appreciated.

Major changes include:
- [x] Specifying several analysis periods with different pivot variants which growth advantages are estimated relative to. (See `config.yaml` for specification here)
- [x] Provisioning data sets for each analysis period (See `workflow/snakemake_rules/prepare_data.smk`)
- [x] Running the innovation model with the specified period for all qualifying locations (See `scripts/run-innovation-model`)

This to be accomplished still:
- [x] Checking Python implementation of `mlr-fitness/data/pango-relationships.nb` for correctness
- [x] Testing of workflow in general.
- [x] Implementing phenotype prediction using DMS data / snakemake.

Note: I've borrowed the  files `scripts/prepare-data.py` and `scripts/collapse-lineages.py` directly from forecasts-ncov. Let me know if there's a better way of doing this.

### CODE REVIEW

**Comment by marlinfiggins** [comment]
I've tried to convert [compare_natural notebook](https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/blob/main/notebooks/compare_natural.ipynb) to a Python script `scripts/compute-phenotype` which can be used to generate phenotype files in specified in `prepare_data.smk` (corresponding rule is `compute_phenotype`).

There's a couple of remaining tasks for this section:

- [x] Ensuring pairs for predictor differences are generated with the parent-variant relationships in `pango_variant_relationships`
- [x] Figure out best way of specifying which phenotypes to generate. I imagine a section in `config.yaml` would be ideal?
- [ ] Processing phenotypes to a single (or collection of) predictors files.
- [x] Testing in general

**Comment by trvrb** [comment]
Thanks so much for diving in here @marlinfiggins. I'm sorry that I didn't notice this PR before you pointed it out to me last month. I just tried working from `rewrite` and I managed to fix some initial Snakemake bugs that were throwing errors. However, I now encounter
```
nextstrain build --cpus 1 . data/gisaid/pango_lineages/global/xbb15/prepared_cases.tsv
Building DAG of jobs...
MissingInputException in rule prepare_clade_data in file /nextstrain/build/workflow/snakemake_rules/prepare_data.smk, line 43:
Missing input files for rule prepare_clade_data:
    output: data/gisaid/pango_lineages/global/xbb15/prepared_cases.tsv, data/gisaid/pango_lineages/global/xbb15/prepared_seq_counts.tsv
    wildcards: data_provenance=gisaid, variant_classification=pango_lineages, geo_resolution=global, analysis_period=xbb15
    affected files:
        data/cases/global.tsv.gz
        data/gisaid/pango_lineages/global.tsv.gz
```

I think that you're assuming that local files like `data/gisaid/pango_lineages/global.tsv.gz` exist? Can you please add to the `README.md` what steps need to be taken to provision data before running Snakemake?

I just did almost exactly this over here: https://github.com/blab/fitness-dynamics?tab=readme-ov-file#provision-metadata-locally.

I can continue review once I know how to provision local data.

--------------

Also, separate question: can we just drop `data/{data_provenance}/{variant_classification}/{geo_resolution}/{analysis_period}/prepared_cases.tsv`? I don't think cases feed into any of the MLR analyses.

**Comment by trvrb** [comment]
Hey @marlinfiggins. I was able to provision data locally and fix some errors to get me to 
```
data/gisaid/pango_lineages/global/xbb15/collapsed_seq_counts.tsv
data/gisaid/pango_lineages/global/xbb15/pango_variant_relationships.tsv
```

However, I can't figure out how to even begin with phenotypes. From `prepare_data.smk` I see I should be able to ask for `predictors/{analysis_period}/{pheno}_clade.csv`. I tried this with `nextstrain build . -j 1 predictors/xbb15/EVEscape_clade.csv` and got the error:
```
InputFunctionException in rule compute_phenotypes in file /nextstrain/build/workflow/snakemake_rules/prepare_data.smk, line 163:
Error:
  AttributeError: 'Wildcards' object has no attribute 'phenotype'
Wildcards:
  analysis_period=xbb15
  pheno=EVEscape
Traceback:
  File "/nextstrain/build/workflow/snakemake_rules/prepare_data.smk", line 165, in <lambda>
```
I'm pretty sure this was an issue with line 165 of:
```
input_data = lambda wildcards: phenos_compare_natural.get(wildcards.phenotype),
```
I just updated this to 
```
input_data = lambda wildcards: phenos_compare_natural.get(wildcards.pheno),
```

**Comment by trvrb** [comment]
(continued...)

However now calling `nextstrain build . -j 1 predictors/xbb15/EVEscape_clade.csv` is giving the error
```
WorkflowError in rule compute_phenotypes in file /nextstrain/build/workflow/snakemake_rules/prepare_data.smk, line 163:
Function did not return str or list of str.
```

Can you please take a look at this? Please add instructions in `README.md` for how to proceed with provisioning local phenotypes.

**Review by trvrb — CHANGES_REQUESTED** [review]
@marlinfiggins ---

Please update README.md with examples of how to actually run this workflow. I'd like to be able to work through the readme to be understand how to interact with the workflow. See https://github.com/blab/fitness-flux for a pretty minimal example of what I mean.

**Comment by trvrb** [comment]
@marlinfiggins: Thanks for providing instructions on how to run workflow. However, I'm running into errors. If I reduce `analysis_period` in `config.yaml` to just:
```
analysis_period:
  xbb15:
    min_date: "2023-01-01"
    max_date: "2023-12-01"
    pivot: "XBB.1.5"
    force_include: "defaults/xbb15/force_include_lineages.txt"
    predictor_names:
      - "spike pseudovirus DMS human sera escape relative to XBB.1.5"
      - "spike pseudovirus DMS ACE2 binding relative to XBB.1.5"
      - "RBD yeast-display DMS ACE2 affinity relative to XBB.1.5"
      - "RBD yeast-display DMS RBD expression relative to XBB.1.5"
      - "RBD yeast-display DMS escape relative to XBB.1.5"
``` 

Update to the latest Docker image with `nextstrain update` and run with `nextstrain build . -j 1 all` I get the following error:
```
python ./scripts/run-innovation-model.py             --seq-counts data/xbb15/collapsed_seq_counts.tsv             --pango-relationships data/xbb15/pango_variant_relationships.tsv             --growth-advantage-path results/xbb15/growth_advantages.tsv             --growth-advantage-delta-path results/xbb15/growth_advantages_delta.tsv             --posterior-path results/xbb15/posteriors             --pivot XBB.1.5
        
Traceback (most recent call last):
  File "/nextstrain/build/./scripts/run-innovation-model.py", line 6, in <module>
    import evofr as ef
  File "/usr/local/lib/python3.10/site-packages/evofr/__init__.py", line 13, in <module>
    from .infer import InferFullRank  # , BlackJaxHandler; InferBlackJax,
  File "/usr/local/lib/python3.10/site-packages/evofr/infer/__init__.py", line 2, in <module>
    from .InferMCMC import InferMCMC, InferNUTS
  File "/usr/local/lib/python3.10/site-packages/evofr/infer/InferMCMC.py", line 10, in <module>
    from .MCMC_handler import MCMCHandler
  File "/usr/local/lib/python3.10/site-packages/evofr/infer/MCMC_handler.py", line 5, in <module>
    from jax._src.random import KeyArray
ImportError: cannot import name 'KeyArray' from 'jax._src.random' (/usr/local/lib/python3.10/site-packages/jax/_src/random.py)
```

Are there dependencies that need updating for this to run?

**Comment by trvrb** [comment]
This can be resolved via https://github.com/blab/evofr/pull/44.

Suggest to update ncov-escape README.md with current installation instructions. This will be `nextstrain update` + running `nextstrain shell` and updating evofr to the latest version ahead of things cascading down to the default Docker image. The readme should have installation instructions in any case.

_I've made this revision in the below commit._

**Comment by trvrb** [comment]
@marlinfiggins ---

After the [update to the Nextstrain docker image](https://github.com/nextstrain/docker-base/actions/runs/12381878622), I'm now longer getting the above jax error. However, if run attempt to run the repo in it's current state without touching `config.yaml` I get the following error:

```
MissingInputException in rule process_metadata in file /nextstrain/build/workflow/snakemake_rules/run_models_over_period.smk, line 2:
Missing input files for rule process_metadata:
    output: data/xbb15_windowed/sequence_counts_by_submission.tsv
    wildcards: analysis_period=xbb15_windowed
    affected files:
        data/gisaid_metadata.tsv.gz
```

The config looks like it should just use what's in `analysis_period.xbb15`. However, if I take `config.yaml` and delete other entries in `analysis_period` and keep only `xbb15` I get different behavior with a different error after it runs through a number of steps:

```
rule download_phenotypes:
    output: data/xbb15/phenotypes/mutation_phenotypes.csv, data/xbb15/phenotypes/mutation_phenotypes_randomized.csv, data/xbb15/phenotypes/lineage_phenotypes.csv, data/xbb15/phenotypes/lineage_phenotypes_randomized.csv
    jobid: 7
    reason: Missing output files: data/xbb15/phenotypes/lineage_phenotypes.csv
    wildcards: analysis_period=xbb15
    resources: tmpdir=/tmp


        python ./scripts/provision-phenotypes.py             --config-path config.yaml             --base-url https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main             --output-path data/xbb15/phenotypes
        
No `output` key in config. Falling back to default files.
Downloading https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/mutation_phenotypes.csv...
Saved to data/xbb15/phenotypes/mutation_phenotypes.csv
Downloading https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/mutation_phenotypes_randomized.csv...
Saved to data/xbb15/phenotypes/mutation_phenotypes_randomized.csv
Downloading https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/lineage_phenotypes.csv...
Failed to download https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/lineage_phenotypes.csv: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/lineage_phenotypes.csv
Downloading https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/lineage_phenotypes_randomized.csv...
Failed to download https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/lineage_phenotypes_randomized.csv: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/jbloomlab/SARS2-spike-predictor-phenos/refs/heads/main/results/lineage_phenotypes_randomized.csv
``` 

Marlin, this doesn't have to be a correct / complete analysis, but I really would like the default analysis and what's specified in the readme to at least _run_. Can you take another look at this? Please try working from a fresh repo to make sure things at least run.

Noting here that if I swap `xbb15` to the provided `jn1` analysis period, the workflow completes successfully. I'd be 100% of okay merging this PR if you can just reduce scope to something like this and then we'll get phenotypic predictors working in a subsequent PR.

**Review by trvrb — CHANGES_REQUESTED** [review]
Blocking now is having the default `config.yaml` / instructions in the readme complete without error. See above comment.

**Comment by marlinfiggins** [comment]
Sorry about this, I've made some changes. 

The bug you were running into was with running the regression prior model. It was attempting to fetch the phenotypes from the wrong files.

The issue here was that I had to switch the code to use the old version of the predictors `clade_phenotypes.csv` present on the `main` branch of [SARS2-spike-predictor-phenos](https://github.com/jbloomlab/SARS2-spike-predictor-phenos). There were several differences in that version of the phenotypes and the one that lives on the [lineage phenotypes PR](https://github.com/jbloomlab/SARS2-spike-predictor-phenos/pull/1) which is named `lineage_phenotypes.csv`. 

Previously, I just grabbed this by hand from the main branch and renamed the relevant columns to be consistent since I expected this PR to be merged by the time we tested this.

For now, I've changed this and the relevant code to use the phenotypes from the main branch, but I'll just revert these changes once the lineage phenotypes PR is properly merged.

**Comment by marlinfiggins** [comment]
I've also removed the window analysis for now until I fix the location of the `gisaid_metadata` file for the windowed analysis.

**Comment by marlinfiggins** [comment]
I've also added the window analysis back and fixed the instructions for provisioning the metadata.

**Comment by trvrb** [comment]
@marlinfiggins --- Thanks so much for humoring me with the detailed instructions. I was able to run this workflow for different analysis periods and everything worked as expected. I like the set up for `data/{analysis_period}/` for sequence counts and variant relationships and the corresponding `results/{analysis_period}/` for model outputs.

**Review by trvrb — APPROVED** [review]
Everything looks great at this point.

**Pull request merged**
